spring:
  sql:
    init:
      mode: always
      schema-location: classpath:schema.sql
  datasource:
    url: jdbc:h2:mem:taskdb
    driverClassName: org.h2.Driver
    username: root
    password:
  h2:
    console:
      enabled: false
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: metrics, prometheus
  endpoint:
    health:
      show-details: always
  info:
    app:
      name: "Task Manager"
      version: "0.0.1"
      description: "This app does something awesome!"